version: '3'
services:
  rabbitmq:
    image: library/rabbitmq:management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    deploy:
      restart_policy:
        condition: on-failure
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      restart_policy:
        condition: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    deploy:
      restart_policy:
        condition: on-failure
  ipfs:
    image: ipfs/go-ipfs:v0.13.1
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    command: [ "daemon", "--enable-gc","--migrate=true", "--agent-version-suffix=docker" ]
    deploy:
      restart_policy:
        condition: on-failure
  tika-extractor:
    image: ipfssearch/tika-extractor:latest
    ports:
      - 8081:8081
    depends_on:
      - ipfs
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-inject-server:
    build: ./extractServer
    depends_on:
      - ipfs
    environment:
      - IPFS_GATEWAY_URL=http://ipfs:8080
    ports:
      - 9999:9999
    volumes:
      - ./out:/out
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-crawler:
    build: .
    depends_on:
      - rabbitmq
      - elasticsearch
      - ipfs
      - tika-extractor
      - jaeger
      - ipfs-inject-server
    environment:
      - TIKA_EXTRACTOR=http://tika-extractor:8081
      - IPFS_API_URL=http://ipfs:5001
      - IPFS_GATEWAY_URL=http://ipfs:8080
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_TRACE_SAMPLER_ARG=1.0
      - SERVER_URL=ipfs-inject-server:9999
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-search-api:
    image: ipfssearch/ipfs-search-api:latest
    ports:
      - 9615:9615
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-sniffer:
    image: ipfssearch/ipfs-sniffer:latest
    depends_on:
      - rabbitmq
      - jaeger
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    deploy:
      restart_policy:
        condition: on-failure
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_TAGS_AS_FIELDS_ALL=true
    depends_on:
      - elasticsearch
    ports:
      - "14268:14268" # HTTP Collector
      - "16686:16686" # Frontend
    command: ["--es.num-shards=1", "--es.num-replicas=0"]
    deploy:
      restart_policy:
        condition: on-failure
