
version: '3'
services:
  rabbitmq:
    image: library/rabbitmq:management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    deploy:
      restart_policy:
        condition: on-failure
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      restart_policy:
        condition: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    deploy:
      restart_policy:
        condition: on-failure
  export-server:
    build: ./extractServer
    ports:
      - 4322:4322 # http server
      - 4321:4321 # subscribe tcp server
      - 8070:8080 # ipfs gateway
      - 5001:5001 # ipfs http RPC
      - 4001:4001
      - 29998:29998
    environment:
      - IPFS_GATEWAY_URL=http://export-server:8080
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./out/:/out/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:5001" ]
      interval: 30s
      timeout: 10s
      retries: 5
  tika-extractor:
    image: ipfssearch/tika-extractor:latest
    ports:
      - 8081:8081
    depends_on:
      - export-server
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-crawler:
    build: .
    depends_on:
      - rabbitmq
      - elasticsearch
      - export-server
      - tika-extractor
      - jaeger
    environment:
      - TIKA_EXTRACTOR=http://tika-extractor:8081
      - IPFS_API_URL=http://export-server:5001
      - IPFS_GATEWAY_URL=http://export-server:8080
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_TRACE_SAMPLER_ARG=1.0
      - SERVER_URL=export-server:29998
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-search-api:
    image: ipfssearch/ipfs-search-api:latest
    ports:
      - 9615:9615
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-sniffer:
    image: ipfssearch/ipfs-sniffer:latest
    depends_on:
      - rabbitmq
      - jaeger
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    deploy:
      restart_policy:
        condition: on-failure
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_TAGS_AS_FIELDS_ALL=true
    depends_on:
      - elasticsearch
    ports:
      - "14268:14268" # HTTP Collector
      - "16686:16686" # Frontend
    command: [ "--es.num-shards=1", "--es.num-replicas=0" ]
    deploy:
      restart_policy:
        condition: on-failure
